module.exports = {
	// IPB : International Performance Benchmarks
	// keys are competition age (CompYear - YOB), value is CPL IPB
	ipb : {
		men : {
			distance : {
				17 : 84,
				18 : 87,
				19 : 89.5,
				20 : 91.5,
				21 : 93.5,
				22 : 94.5,
				23 : 95,
			},
			sprint : {
				17 : 84.5,
				18 : 87.5,
				19 : 90,
				20 : 92,
				21 : 94,
				22 : 95,
				23 : 96,
			},
		},

		women : {
			distance : {
				17 : 81,
				18 : 84,
				19 : 86.5,
				20 : 88.5,
				21 : 90.5,
				22 : 92,
				23 : 93,
			},
			sprint : {
				17 : 83.5,
				18 : 86.5,
				19 : 89,
				20 : 91,
				21 : 93,
				22 : 94,
				23 : 95,
			},
		},

		numDigitsForPct : 2,
	},

	// the set of points calculations to perform
	teams : [
		{
			name    : 'Ontario Junior Ski Team',
			minAge  : 15,
			maxAge  : 17,
			showIPB : false,
		},
		{
			name    : 'Ontario Ski Team',
			minAge  : 18,
			maxAge  : 23,
			showIPB : true,
		},
	],

	districtComp : {
		maxAge              : 23,
		numSkiersForPoints  : 10,
		numSkiersForDetails : 15,
	},

	// http://apps.cccski.com/main.asp?lan=0&cmd=cll&id=5&Param1=
	clubs : {
		SOD : [
			'Arrowhead Nordic Ski Club',
			'Barrie Cross Country',
			'Beaver Valley Nordic Ski Club',
			'Bruce Ski Club',
			'Eden Mills Nordic Ski Club',
			'Etobicoke X-Country Ski Club',
			'Five Winds Ski Touring Club',
			'Georgian Bay Nordic',
			'Georgian Nordic Ski and Canoe Club',
			'Georgian Nordic Outdoor Activity Centre',
			'Haliburton Highlands Nordic Trails Association',
			'Highlands Trailblazers',
			'Kawartha Nordic Ski Club',
			'Kincardine Cross Country Ski Club',
			'Lifeski Academy Ski Club',
			'Midland Ski Club',
			'Mono Nordic Club',
			'Ontario Para Nordic Renegades',
			'Owen Sound X-C Ski Club',
			'Pinestone Resort Trails Ski Club',
			'Polecats (Wildwood)',
			'Scarborough Cross Country Ski Club',
			'Tay Valley Cross Country Ski Club',
			'Team Hardwood',
			'Trakkers X-C Ski Club',
			'University of Toronto Nordic Ski Team',
			'Waterloo Region Nordic Sports Club',
		],
		NCD : [
			'Brittania Winter Trail Association',
			'Carleton University Nordic Ski Team',
			'Chelsea Nordiq (Ontario)',
			'Deep River Cross Country Ski Club',
			'Kanata Nordic',
			'Mississippi Valley Ski Club',
			'Nakkertok Nordic (Ontario)',
			'Opeongo Hills Nordic Ski Club',
			'Orleans Nordic Ski Club',
			'Ottawa Racers Ski Club',
			'Pembroke & Area Cross Country Ski Club Inc.',
			'Skinouk (Ontario)',
			'Triangle X-Country Ski Club of Brockville',
			'West Carleton Nordic Ski Club',
			'XC Chelsea Masters',
			'XC Ottawa',
			'xczone',
		],
		NOD : [
			'BioSki Cross Country Ski & Snowshoe Club',
			'Blind River Cross Country Ski Club',
			'Cochrane Cross Country Ski Club',
			'Capreol Cross Country Ski Club',
			'Englehart Nordic Ski Club',
			'Iroquois Falls Cross Country Ski Club',
			'Kapuskasing Nordic Skiers',
			'Laurentian Nordic Ski Club',
			'Manitoulin Nordic Ski Club',
			'North Bay Nordic Ski Club',
			'Onaping Falls Nordics Ski Club',
			'Porcupine Ski Runners',
			'Soo Finnish Nordic Ski Club',
			'Temiskaming Nordic Ski Club',
			'Walden Cross Country',
			'Wawa Cross-Country Ski Club',
		],
		LSSD : [
			'Beaten Path Nordic Trails',
			'Big Thunder Nordic Ski Club',
			'Dryden Ski Club',
			'Finlandia Association of Thunder Bay',
			'Geraldton Nordic Ski Club',
			'Hearst Cross Country Ski Club',
			'Kamview Jackrabbits Ski Program',
			'Kenora Nordic & Biathlon Club (Ontario)',
			'Lakehead Superior Nordic Association',
			'Lappe Nordic Ski Club',
			'Marathon Cross Country Ski Club',
			'National Team Development Centre-Thunder Bay',
			'Northern Trails Ski Club Inc.',
			'Rainy Lake Nordic Ski Club',
			'Red Lake District Cross Country Ski Club',
			'Rendezvous Cross Country Ski Club',
			'Sioux Lookout Nordic Nomads',
			'Superior Cross Country Ski Club',
		],
	},
};
